### ISSUE TITLE
Can't create new notebooks or folders

### ISSUE THREAD

**Issue by rsmulktis** [uktrade/jupyters3#8] opened 2019-08-31 11:51 UTC
If i'm in a directory, say "/Admin" (applies to ANY dir, including the root "/" too) and I try to create a new notebook or folder I get an error as such: "No such directory: /Admin". At the top of the directory lists, I see a double "/" like this: "[FolderIcon] / /Admin", which probably is indicative of the issue. Is this something wrong with my configuration?

**Comment by michalc** [comment] 2019-08-31 11:57
Hi @rsmulktis, can you confirm what version of JupyterS3 you're using, as well as notebook (and jupyterlab if you're using it).

> Is this something wrong with my configuration?

Not sure: can you post your configuration (without any keys)?

**Comment by rsmulktis** [comment] 2019-08-31 12:08
Python: 3.7.3
JupyterS3: 0.0.36
Notebook: 6.0.0

I'm using Jupyter, not JupyterLab right now.

Here's my config just substituting some strings but keeping their format/structure:

`python
from jupyters3 import JupyterS3, JupyterS3SecretAccessKeyAuthentication
c.NotebookApp.contents_manager_class = JupyterS3
c.JupyterS3.aws_region = 'us-west-2'
c.JupyterS3.aws_s3_bucket = 'my-bucket-name'
c.JupyterS3.aws_s3_host = 's3-us-west-2.amazonaws.com'
c.JupyterS3.prefix = ''
c.JupyterS3.authentication_class = JupyterS3SecretAccessKeyAuthentication
c.JupyterS3SecretAccessKeyAuthentication.aws_access_key_id = '...'
c.JupyterS3SecretAccessKeyAuthentication.aws_secret_access_key = '...'
`

**Comment by michalc** [comment] 2019-08-31 12:24
Hi @rsmulktis,

Thanks for the info. A few more questions...

- Does anything appear in the console log?
- Does the same issue occur with notebook 5.7.8 or notebook, 6.0.1, and with the latest jupyters3?
- What version of tornado is running?

Thanks

**Comment by rsmulktis** [comment] 2019-08-31 13:11
I rebuilt my container w/ jupyters3 v0.39. Now I get this error: "Cannot POST to files, use PUT instead."

This continues to have notebook 6.0.0 and python 3.7.3. Tornado is v6.0.3. 

This is what I see in the log:

```
2019-08-31 09:07:44[W 13:07:44.990 NotebookApp] 400 POST /api/contents (108.78.212.251): Cannot POST to files, use PUT instead.
2019-08-31 09:07:44[W 13:07:44.990 NotebookApp] Cannot POST to files, use PUT instead.
2019-08-31 09:07:44[W 13:07:44.990 NotebookApp] 400 POST /api/contents (108.78.212.251) 19.30ms referer=http://my.jupyter-server.com:port/tree
```

**Comment by rsmulktis** [comment] 2019-09-03 10:21
Tried with notebook=5.7.8 but same issues. 

Next, I tried playing with the "prefix" and THAT seems to point in a direction. If I configured a non-empty-string prefix then I was able to make directories, create new files, etc. This helps explain why I was seeing "/ /[dir name]" in Jupyter. You probably have logic that isn't properly handling an empty string so its concatenating two forward slashes. If I gave prefix "/" it would work, but would put notebooks in an s3 folder that had a blank name. 

So, I think I have a workaround for the current version by using a sub-folder in my bucket. But, hopefully an easy bug for you!

**Comment by michalc** [comment] 2019-11-24 12:01
I have reproduced the issue: with notebook and an empty prefix, creating notebooks in the root fails with the error "Cannot POST to files, use PUT instead."

Using JupyterLab, there is no error and creating notebooks in the root works fine. Or, as you have noted, a non-empty prefix also works fine.

**Comment by michalc** [comment] 2019-11-24 12:19
I believe the issue is fixed, and released in v.0.0.40. 

Closing. If this issue still occurs, feel free to reopen.

**Closed by michalc** 2019-11-24 12:19 UTC
