### ISSUE TITLE
Cannot open a new notebook in Jupyter Notebook

### ISSUE THREAD

**Issue by withsmilo** [uktrade/jupyters3#7] opened 2019-08-13 04:27 UTC
Hi, 
I installed v0.0.37 of jupyters3 and set the configuration to use S3 as a backend. Everything looks fine, but I found a bug that I cannot open a new notebook with the following error.
```
[E 04:23:48.857 NotebookApp] Uncaught exception GET /notebooks/Untitled1.ipynb (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/notebooks/Untitled1.ipynb', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/home1/datachain/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home1/datachain/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/home1/datachain/opt/conda/lib/python3.6/site-packages/notebook/notebook/handlers.py", line 86, in get
        if model['type'] != 'notebook':
    TypeError: '_asyncio.Future' object is not subscriptable
[E 04:23:48.859 NotebookApp] {
      "Host": "127.0.0.1:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
      "Sec-Fetch-Mode": "navigate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://127.0.0.1:8888/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9,ko;q=0.8",
      "Cookie": "username-127-0-0-1-8888=\"2|1:0|10:1565668713|23:username-127-0-0-1-8888|44:Yzg0YjE5ODg2MjNjNDI4NGFmYjYwMDViYWY0YjM5NzU=|b33944bd4ef3638d27bcd54a2f02a49b844dedd3020f4255b3c33031ad50708a\"; _xsrf=2|9b58d766|0c7abf63807a857721c45333d23add3d|1565668713"
    }
[E 04:23:48.859 NotebookApp] 500 GET /notebooks/Untitled1.ipynb (172.17.0.1) 3.40ms referer=http://127.0.0.1:8888/tree
```

**Comment by withsmilo** [comment] 2019-08-13 04:37
After downgrading jupyters3 from v0.0.37 to v0.0.36, I can open a new notebook. I think that the latest commit(https://github.com/uktrade/jupyters3/commit/b92390f0a488ce59fd3e9efc4fa814d43fc4055f) seems to be buggy.

**Comment by michalc** [comment] 2019-08-13 07:26
Hi,

Thanks for the report. Can I check which version of notebook you’re running? (The latest JupyterS3 will only work with >= 6)

Thanks,

Michal

**Comment by michalc** [comment] 2019-08-13 07:51
I have now reproduced the issue with notebook 6.0.0. Will investigate

**Comment by withsmilo** [comment] 2019-08-13 07:51
@michalc 
My version is here,
```
# jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : not installed
ipython          : 7.7.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : not installed
nbconvert        : 5.6.0
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.
```

**Comment by withsmilo** [comment] 2019-08-13 07:52
@michalc 
Thanks for quick reply!

**Comment by michalc** [comment] 2019-08-13 07:53
Ah no problem.

After an extremely brief check, it looks like the issue is limited to Jupyter Notebook: JupyterLab is fine.

**Comment by withsmilo** [comment] 2019-08-13 07:54
Thanks for sharing it with me. I will try JupyterLab instead of Jupyter Notebook.

**Comment by saulius** [comment] 2019-08-29 08:13
Stumbled upon this as well. Notebook export functionality in Jupyterlab throws a 500 with the same exception.

**Comment by michalc** [comment] 2019-08-29 08:23
@withsmilo @saulius Have reverted the offending commit in https://github.com/uktrade/jupyters3/commit/a1aa51adf43dc28aef5ae94db5fff5bc38a0f04b, and released a new version in pypi. I suspect there will need to more changes to notebook to support those particular functions be not blocking that I originally thought.

Closing the issue, but feel free to reopen if the issue persists in v0.0.38

**Closed by michalc** 2019-08-29 08:23 UTC
